- name: prometheus server
  ansible.builtin.import_tasks: # loading server.yml file
    file: server.yml
  when: prometheus_server

- name: node exporter
  ansible.builtin.import_tasks:
    file: exporter.yml
  when: node_exporter
