- name: Update Prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Update Prometheus Configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/prometheus/{{ item }}.yml
  loop: "{{ alert_files }}"

- name: Restart Prometheus Service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Check prometheus is started or not
  ansible.builtin.shell: netstat -lntp | grep 9090


