- name: Update Prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Update Prometheus Configuration
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: Update Prometheus Configuration
  ansible.builtin.template:
    src: service-down-alerts.yml
    dest: /opt/prometheus/service-down-alerts.yml

- name: Restart Prometheus Service
  ansible.builtin.systemd:
    name: prometheus
    state: restarted


