- name: Create Application User
  ansible.builtin.user:
    name: roboshop

- name: Delete Old directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create App directory
  ansible.builtin.file:
    path: /app
    state: directory

## Download from AWS s3 artifact
#- name: Download and extract {{ component }} content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: /app
#    remote_src: yes


## Download from Nexus Repository
- name: Download and extract {{ component }} content
  ansible.builtin.unarchive:
   # src: http://{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.user', region ='us-east-1' ) }}:{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.pass', region ='us-east-1' ) }}@nexus.saraldevops.site:8081/repository/{{ component }}/{{ component }}-{{ app_version }}.zip
    src: http://{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.user', region='us-east-1') }}:{{ lookup('amazon.aws.aws_ssm', '{{env}}.nexus.pass', region='us-east-1') }}@nexus.saraldevops.site:8081/repository/{{component}}/{{component}}-{{app_version}}.zip

    dest: /app
    remote_src: yes