- name: Configure NodeJS Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.shell: sudo yum install nodejs -y


- name: App pre-req setup
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install NodeJS dependencies
  ansible.builtin.shell: npm install
  args:
      chdir: /app

#  community.general.npm:
#    path: /app # here everything is in /app only , look app-prereq.yml file

- name: Schema Setup
  ansible.builtin.import_tasks:
    file: schema-setup.yml
  when: schema_type is defined


- name: SystemD setup
  ansible.builtin.import_tasks:
    file: systemd-setup.yml

