- name: MongoDB Schema
  when: schema_type == "mongo"
  block:
    - name: Setup MongoDB Repo File
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo
      #when: schema_type == "mongo"

    - name: Install Mongo Client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed
     # when: schema_type == "mongo"

    - name: Load Schema
      ansible.builtin.shell: sudo mongo --host {{ lookup('amazon.aws.aws_ssm', '{{env}}.mongodb.mongodb_url', region ='us-east-1' ) }} </app/schema/{{component}}.js

- name: Mysql Schema
  when: schema_type == "mysql"
  block:
    - name: Install Mysql client
      ansible.builtin.yum:
        name: mysql
        state: installed


    - name: Load Schema
      ansible.builtin.shell: sudo mysql -h {{ lookup('amazon.aws.aws_ssm', '{{env}}.mysql.mysql_url', region ='us-east-1' ) }} -uroot -p{{ lookup('amazon.aws.aws_ssm', '{{env}}.{{component}}.password', region ='us-east-1' ) }} < /app/schema/{{component}}.sql