- name: Copy systemd config file
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /ssh centosetc/systemd/system/{{component}}.service

- name: Start Service
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: restarted
    enabled: true
    daemon-reload: true

